import type { ServiceSeed } from "./types";

/** Default service catalogue. Seeded into the database and used as the
 *  public-site fallback before a database is provisioned (PRD §8). */
export const serviceCategories = [
  { slug: "engineering", name: "Engineering", description: "Websites, storefronts and the systems behind them.", icon: "Code2", position: 1 },
  { slug: "growth", name: "Growth & Marketing", description: "Search, paid media, email and conversion work.", icon: "TrendingUp", position: 2 },
  { slug: "creative", name: "Brand & Creative", description: "Identity, design systems and campaign assets.", icon: "Palette", position: 3 },
] as const;

export const services: ServiceSeed[] = [
  {
    slug: "web-development",
    title: "Web Development",
    categorySlug: "engineering",
    tagline: "Fast, accessible, conversion-shaped websites and web apps.",
    shortDescription: "Custom websites and web applications engineered on Next.js and TypeScript — fast by default, accessible by design, and built to be edited without a developer.",
    longDescription: "We build the marketing site and the product behind it. Every HYASCKA build starts from measurable outcomes — page speed, conversion rate, organic visibility — and works backwards into architecture. You get server-rendered pages that score in the green on Core Web Vitals, a component system your team can extend, and a CMS layer so content changes never queue behind a deployment.\n\nWe work in the open: a staging environment from day one, weekly demos, and a rollout plan that includes DNS, SSL, analytics and a rollback path before anything touches production.",
    icon: "Code2",
    deliverables: ["Technical discovery and information architecture", "Design system and responsive UI build", "Next.js App Router implementation with TypeScript", "CMS integration so content is editable without code", "Core Web Vitals optimisation pass", "Analytics, consent and event tracking setup", "Staging environment, CI checks and production deployment", "30 days of post-launch support"],
    technologies: ["Next.js", "TypeScript", "React", "Tailwind CSS", "PostgreSQL", "Prisma", "Vercel", "Cloudflare"],
    processSteps: [
      { title: "Discover", detail: "Goals, audience, competitors, constraints and success metrics agreed in writing." },
      { title: "Architect", detail: "Sitemap, content model, component inventory and performance budget." },
      { title: "Design", detail: "Design system first, then key templates — reviewed on real devices." },
      { title: "Build", detail: "Two-week increments on a live staging URL with automated checks on every push." },
      { title: "Launch", detail: "DNS/SSL cutover, analytics verification, Lighthouse pass and a rollback plan." },
      { title: "Grow", detail: "Post-launch measurement, CRO experiments and iteration." },
    ],
    timeline: "4–10 weeks depending on scope",
    pricingModel: "STARTING_FROM",
    startingPrice: 180000,
    currency: "BDT",
    featured: true,
    position: 1,
    features: [
      { title: "Performance budget enforced", detail: "Every page ships against an agreed JS and image budget, checked in CI — not measured after launch." },
      { title: "Editable without a developer", detail: "Hero copy, sections, services, pricing and SEO fields all live in the dashboard." },
      { title: "Accessible to WCAG 2.1 AA", detail: "Keyboard paths, focus states, contrast and reduced-motion handled as build requirements." },
      { title: "Own your stack", detail: "Standard Next.js, standard PostgreSQL. No proprietary lock-in, full repository handover." },
    ],
    faqs: [
      { question: "Do we own the code?", answer: "Yes. The repository, the database and every credential are yours from day one. We work inside your GitHub organisation if you have one." },
      { question: "Can our team edit content afterwards?", answer: "That is the point of the CMS layer. Homepage sections, services, blog, case studies, pricing and SEO metadata are all form-based edits with preview-before-publish." },
      { question: "What happens after launch?", answer: "Thirty days of included support covers bugs and small changes. After that most clients move to a monthly retainer for iteration and growth work." },
    ],
    packages: [
      {
        name: "Launch",
        summary: "A focused marketing site for a team that needs to be credible quickly.",
        price: 180000,
        billingCycle: "one-time",
        pricingModel: "FIXED",
        features: ["Up to 8 pages", "Design system + responsive build", "CMS for all page content", "Core Web Vitals pass", "Basic schema + sitemap", "30 days support"],
        highlighted: false,
      },
      {
        name: "Growth",
        summary: "The full agency-grade site with content operations built in.",
        price: 380000,
        billingCycle: "one-time",
        pricingModel: "FIXED",
        features: ["Up to 20 pages + blog + case studies", "Custom section builder", "Advanced SEO + structured data", "Lead routing and CRM handoff", "A/B-ready CTA framework", "90 days support"],
        highlighted: true,
      },
      {
        name: "Platform",
        summary: "Website plus the application logic behind it.",
        price: null,
        billingCycle: "project",
        pricingModel: "CUSTOM_QUOTE",
        features: ["Everything in Growth", "Client portal / dashboards", "Payments and invoicing", "Role-based access control", "Third-party integrations", "Dedicated delivery team"],
        highlighted: false,
      },
    ],
  },
  {
    slug: "ecommerce-development",
    title: "E-commerce Development",
    categorySlug: "engineering",
    tagline: "Storefronts that load fast and check out faster.",
    shortDescription: "Headless and platform-based commerce builds focused on the two numbers that matter: how quickly a page paints and how many carts convert.",
    longDescription: "Most stores do not lose money on traffic — they lose it between the product page and the confirmation screen. We rebuild that path: fast catalogue rendering, honest stock and delivery information, a checkout with the fewest possible steps, and payment methods your customers actually use.\n\nWe work on headless Next.js storefronts as well as on top of existing platforms, and we instrument the funnel so every later decision is made from data rather than opinion.",
    icon: "ShoppingCart",
    deliverables: ["Catalogue and merchandising architecture", "Product, category and search experience", "Optimised cart and checkout flow", "Local payment method integration", "Order, inventory and fulfilment integration", "Commerce analytics and funnel event tracking", "Speed optimisation for catalogue pages", "Launch and post-launch monitoring"],
    technologies: ["Next.js", "Shopify / Medusa", "Stripe", "SSLCommerz", "bKash", "PostgreSQL", "Algolia"],
    processSteps: [
      { title: "Audit", detail: "Funnel measurement, drop-off analysis and technical baseline." },
      { title: "Model", detail: "Catalogue structure, variants, pricing rules and tax/shipping logic." },
      { title: "Design", detail: "Product and checkout templates designed mobile-first." },
      { title: "Build", detail: "Storefront, checkout and integrations delivered incrementally." },
      { title: "Launch", detail: "Payment and order testing end-to-end before cutover." },
      { title: "Optimise", detail: "Conversion experiments on the highest-traffic paths." },
    ],
    timeline: "6–12 weeks",
    pricingModel: "STARTING_FROM",
    startingPrice: 280000,
    currency: "BDT",
    featured: true,
    position: 2,
    features: [
      { title: "Checkout built for the drop-off points", detail: "Guest checkout, saved addresses, clear delivery expectations and error states that recover instead of dead-ending." },
      { title: "Local payments included", detail: "bKash, Nagad, bank transfer and card gateways configured and reconciled, not just linked." },
      { title: "Catalogue that stays fast at scale", detail: "Static generation with on-demand revalidation, so a thousand products load like ten." },
      { title: "Real funnel instrumentation", detail: "View, add-to-cart, checkout start and purchase events wired to GA4 and server-side conversions." },
    ],
    faqs: [
      { question: "Can you work with our existing store?", answer: "Yes. We frequently keep an existing platform as the commerce backend and replace only the storefront, which is the lowest-risk way to get a speed and conversion win." },
      { question: "Do you handle payment gateway approval?", answer: "We prepare the integration and the technical documentation gateways ask for; the merchant account itself has to be opened in your company's name." },
    ],
  },
  {
    slug: "seo",
    title: "Search Engine Optimisation",
    categorySlug: "growth",
    tagline: "Compounding organic growth, measured in pipeline.",
    shortDescription: "Strategy, content and technical work aimed at rankings that convert — reported against revenue, not vanity keyword counts.",
    longDescription: "SEO stops being guesswork when it is tied to a commercial model. We start from the searches that indicate buying intent for your service, map them to pages you either have or need, then fix whatever is stopping those pages from ranking — technical, content or authority.\n\nEvery month you get a report that shows movement in the keywords that matter, the pages that gained or lost, and what we are doing next. No 500-row keyword dumps.",
    icon: "Search",
    deliverables: ["Technical SEO audit and prioritised fix list", "Keyword and search intent mapping", "On-page optimisation across priority templates", "Content plan aligned to the buying journey", "Internal linking architecture", "Structured data implementation", "Monthly reporting against agreed KPIs", "Search Console and analytics configuration"],
    technologies: ["Google Search Console", "GA4", "Ahrefs / Semrush", "Screaming Frog", "Schema.org", "Looker Studio"],
    processSteps: [
      { title: "Baseline", detail: "Current visibility, technical health and competitor gap analysis." },
      { title: "Prioritise", detail: "Fixes ranked by effort against expected traffic value." },
      { title: "Fix", detail: "Technical remediation and on-page optimisation shipped in batches." },
      { title: "Publish", detail: "Content produced against the intent map." },
      { title: "Earn", detail: "Digital PR and link acquisition for competitive terms." },
      { title: "Report", detail: "Monthly review of movement, revenue attribution and next actions." },
    ],
    timeline: "Ongoing, first results typically 8–16 weeks",
    pricingModel: "MONTHLY_RETAINER",
    startingPrice: 45000,
    currency: "BDT",
    featured: true,
    position: 3,
    features: [
      { title: "Intent-mapped, not keyword-stuffed", detail: "We rank pages for what a buyer actually types before they buy, then measure the conversions from those sessions." },
      { title: "Technical debt cleared first", detail: "No content plan survives a crawl budget problem. The audit fixes come first." },
      { title: "Reported against revenue", detail: "Sessions are context. Leads, qualified enquiries and closed revenue are the report." },
      { title: "Works with your developers", detail: "If you have an in-house team we hand over precise, ticket-ready fixes instead of a PDF." },
    ],
    faqs: [
      { question: "How long before we see results?", answer: "Technical fixes can move things within weeks. Competitive commercial terms are typically a three to six month curve. We set expectations per keyword group in the first month." },
      { question: "Do you guarantee rankings?", answer: "No one honestly can, and anyone who does is selling something else. We commit to the work, the reporting and the leading indicators." },
    ],
    packages: [
      {
        name: "Foundation",
        summary: "For sites that need the technical base fixed before anything else.",
        price: 45000,
        billingCycle: "per month",
        pricingModel: "MONTHLY_RETAINER",
        features: ["Technical audit + fixes", "Keyword and intent map", "On-page optimisation", "Monthly reporting"],
        highlighted: false,
      },
      {
        name: "Growth",
        summary: "Content engine plus ongoing optimisation.",
        price: 95000,
        billingCycle: "per month",
        pricingModel: "MONTHLY_RETAINER",
        features: ["Everything in Foundation", "4 optimised articles / month", "Internal linking programme", "Conversion tracking", "Quarterly strategy review"],
        highlighted: true,
      },
      {
        name: "Authority",
        summary: "Competitive markets that need links and digital PR.",
        price: null,
        billingCycle: "per month",
        pricingModel: "CUSTOM_QUOTE",
        features: ["Everything in Growth", "Digital PR and link acquisition", "Programmatic / scaled landing pages", "Dedicated strategist"],
        highlighted: false,
      },
    ],
  },
  {
    slug: "local-seo",
    title: "Local SEO",
    categorySlug: "growth",
    tagline: "Own the map pack in the areas you actually serve.",
    shortDescription: "Google Business Profile, local landing pages, citations and review strategy for businesses that sell within a geography.",
    longDescription: "For a business with a service area, the map pack is the shopfront. Local SEO is a different discipline from national organic search: proximity, prominence and consistency of business data decide who appears.\n\nWe optimise the profile, build the location pages that support it, clean up inconsistent listings across directories, and put a review generation system in place so the prominence signal keeps growing.",
    icon: "MapPin",
    deliverables: ["Google Business Profile optimisation", "Location and service-area landing pages", "Citation audit and NAP cleanup", "Review generation workflow", "Local schema markup", "Local keyword tracking", "Competitor map-pack analysis", "Monthly local visibility report"],
    technologies: ["Google Business Profile", "Local schema", "BrightLocal", "GA4"],
    processSteps: [
      { title: "Audit", detail: "Profile completeness, citation consistency and current map-pack position." },
      { title: "Fix", detail: "Correct and standardise business data everywhere it appears." },
      { title: "Build", detail: "Location pages with genuinely distinct, useful content." },
      { title: "Amplify", detail: "Reviews, posts and local content cadence." },
      { title: "Track", detail: "Grid-based rank tracking across the service area." },
      { title: "Iterate", detail: "Monthly adjustments based on movement." },
    ],
    timeline: "Ongoing, first movement in 4–8 weeks",
    pricingModel: "MONTHLY_RETAINER",
    startingPrice: 25000,
    currency: "BDT",
    featured: false,
    position: 4,
    features: [
      { title: "Grid rank tracking", detail: "We track position across a geographic grid, not a single office pin, so you can see the real coverage." },
      { title: "Review system, not review begging", detail: "A workflow that asks the right customer at the right moment, integrated with your delivery process." },
      { title: "Genuinely distinct location pages", detail: "Duplicated city pages get filtered. Ours are written to be useful in each area." },
      { title: "Citation consistency", detail: "One authoritative business record, propagated and monitored." },
    ],
    faqs: [
      { question: "We have multiple branches — can you handle that?", answer: "Yes. Multi-location work uses a location hierarchy, per-branch profiles and a shared content system so quality does not drop as branches are added." },
    ],
  },
  {
    slug: "technical-seo",
    title: "Technical SEO",
    categorySlug: "growth",
    tagline: "Fix what is stopping search engines from valuing your site.",
    shortDescription: "Crawlability, indexation, site speed, structured data and migration safety — the engineering half of search.",
    longDescription: "Technical SEO is where most content investment quietly leaks. Pages that are not crawled, canonical rules that cannibalise, JavaScript that hides content from the renderer, or a migration that dropped a third of the URL map.\n\nWe run a full crawl and log-file analysis, produce a prioritised remediation list your developers can action, and can implement the fixes ourselves when that is faster.",
    icon: "Gauge",
    deliverables: ["Full crawl and log-file analysis", "Indexation and canonicalisation strategy", "Core Web Vitals remediation plan", "JavaScript rendering audit", "Structured data implementation and validation", "XML sitemap and robots architecture", "Migration planning and redirect mapping", "Post-fix verification report"],
    technologies: ["Screaming Frog", "Google Search Console", "Lighthouse CI", "Schema.org", "Cloudflare"],
    processSteps: [
      { title: "Crawl", detail: "Full-site crawl plus log-file review of what search engines actually fetch." },
      { title: "Diagnose", detail: "Rank issues by traffic at risk and effort to fix." },
      { title: "Specify", detail: "Ticket-ready fixes with acceptance criteria." },
      { title: "Implement", detail: "We ship the fixes or support your team shipping them." },
      { title: "Verify", detail: "Re-crawl and Search Console confirmation." },
      { title: "Monitor", detail: "Ongoing alerting on indexation and vitals regressions." },
    ],
    timeline: "2–6 weeks for the audit and first fix wave",
    pricingModel: "STARTING_FROM",
    startingPrice: 85000,
    currency: "BDT",
    featured: false,
    position: 5,
    features: [
      { title: "Log files, not just crawls", detail: "What Googlebot actually requests tells you far more than a simulated crawl." },
      { title: "Migration insurance", detail: "URL mapping, redirect testing and a staged cutover — the single highest-risk SEO event, handled properly." },
      { title: "Vitals treated as engineering", detail: "LCP, INP and CLS fixed at the code level, not with a caching plugin." },
      { title: "Handover-ready output", detail: "Every finding becomes a ticket with a reproduction, a fix and an acceptance test." },
    ],
    faqs: [
      { question: "We are replatforming — when should you be involved?", answer: "Before the URL structure is decided. Involving us after launch means recovering lost rankings instead of protecting them." },
    ],
  },
  {
    slug: "link-building",
    title: "Link Building & Digital PR",
    categorySlug: "growth",
    tagline: "Authority earned through coverage, not bought in bulk.",
    shortDescription: "Editorially earned links from relevant publications through data stories, expert commentary and genuine outreach.",
    longDescription: "Link building only works now if the link would have been given anyway. We create reasons to be cited — original data, expert commentary, useful tools — and run outreach to publications that already write about your market.\n\nEvery placement is reported with the URL, the referring domain metrics and the anchor, so you can audit exactly what was earned.",
    icon: "Link2",
    deliverables: ["Backlink profile and competitor gap audit", "Linkable asset strategy", "Data-led content and outreach campaigns", "Journalist and publication outreach", "Digital PR campaign management", "Anchor text and risk management", "Toxic link identification and disavow", "Monthly placement report"],
    technologies: ["Ahrefs", "Semrush", "Muck Rack", "Google Search Console"],
    processSteps: [
      { title: "Audit", detail: "Existing profile, competitor gaps and risk assessment." },
      { title: "Ideate", detail: "Assets that a journalist in your sector would genuinely use." },
      { title: "Produce", detail: "Research, data and creative built to a publication standard." },
      { title: "Outreach", detail: "Targeted, personalised pitching — never bulk mail." },
      { title: "Secure", detail: "Placements confirmed, tracked and reported." },
      { title: "Protect", detail: "Ongoing monitoring for negative SEO and toxic links." },
    ],
    timeline: "Ongoing, campaigns run 6–10 weeks",
    pricingModel: "MONTHLY_RETAINER",
    startingPrice: 65000,
    currency: "BDT",
    featured: false,
    position: 6,
    features: [
      { title: "Relevance over raw DR", detail: "A relevant link from a trade publication beats a high-authority link from an unrelated site." },
      { title: "Full transparency", detail: "Every placement reported with URL, domain, anchor and date. Nothing hidden behind a summary metric." },
      { title: "No link farms, no PBNs", detail: "We do not place links on networks that put your domain at risk." },
      { title: "Assets you keep", detail: "The data studies and tools we build stay on your domain and keep earning links." },
    ],
    faqs: [
      { question: "How many links per month?", answer: "Volume is the wrong target. We commit to campaign output and report placements; a strong data campaign can earn more in one week than a year of manual placements." },
    ],
  },
  {
    slug: "digital-marketing",
    title: "Digital Marketing & Paid Media",
    categorySlug: "growth",
    tagline: "Paid acquisition with a cost-per-qualified-lead you can defend.",
    shortDescription: "Google, Meta and LinkedIn campaigns built around offer, landing page and measurement — not just bid management.",
    longDescription: "Paid media exposes every weakness in the funnel at speed. We take responsibility for the whole path: the offer, the creative, the landing page and the tracking that proves what happened.\n\nServer-side conversion tracking means the platforms keep optimising accurately even as browser signal degrades, and your reporting matches your CRM instead of contradicting it.",
    icon: "TrendingUp",
    deliverables: ["Channel and budget strategy", "Campaign structure and build", "Ad creative and copy production", "Landing page design and build", "Conversion tracking including server-side events", "Audience and remarketing architecture", "Weekly optimisation and testing", "Monthly performance and spend reporting"],
    technologies: ["Google Ads", "Meta Ads", "LinkedIn Ads", "GA4", "Google Tag Manager", "Meta Conversions API"],
    processSteps: [
      { title: "Model", detail: "Target cost per acquisition derived from your actual close rate and value." },
      { title: "Build", detail: "Account structure, audiences, creative and landing pages." },
      { title: "Instrument", detail: "Browser and server-side tracking verified before spend starts." },
      { title: "Launch", detail: "Controlled budget with a clear learning plan." },
      { title: "Optimise", detail: "Weekly iteration on creative, audience and bidding." },
      { title: "Scale", detail: "Increase spend only where unit economics hold." },
    ],
    timeline: "2–3 weeks to launch, then ongoing",
    pricingModel: "MONTHLY_RETAINER",
    startingPrice: 55000,
    currency: "BDT",
    featured: true,
    position: 7,
    features: [
      { title: "Server-side conversions", detail: "Meta CAPI and GA4 server events keep optimisation accurate through ad blockers and iOS restrictions." },
      { title: "Landing pages included", detail: "We do not send paid traffic to a page we cannot change." },
      { title: "Lead quality, not lead count", detail: "Qualified-lead reporting fed back from your CRM, so bidding optimises toward revenue." },
      { title: "Transparent spend", detail: "You own the ad accounts and see every figure. Management fee separate from media spend." },
    ],
    faqs: [
      { question: "What budget do we need to start?", answer: "Enough to gather statistically meaningful data — typically the equivalent of 30–50 target conversions per month. We will tell you honestly if a budget is too small to learn from." },
      { question: "Do you own our ad accounts?", answer: "No. Accounts are created in your business manager. If we part ways, everything stays with you." },
    ],
  },
  {
    slug: "social-media-marketing",
    title: "Social Media Marketing",
    categorySlug: "growth",
    tagline: "A publishing system, not a posting schedule.",
    shortDescription: "Content strategy, production and community management across the platforms where your buyers actually spend time.",
    longDescription: "Social works when it is a distribution system for a point of view, not a calendar to fill. We define the narrative, build a repeatable production process, and manage the channels day to day.\n\nEverything is measured against a business outcome — profile visits to site, saves and shares as intent signals, DMs and enquiries as pipeline.",
    icon: "Share2",
    deliverables: ["Channel strategy and positioning", "Content pillars and monthly calendar", "Design and short-form video production", "Copywriting in your brand voice", "Scheduling and publishing", "Community management and response handling", "Influencer and partnership coordination", "Monthly performance report"],
    technologies: ["Meta Business Suite", "LinkedIn", "Buffer / Later", "Canva", "Adobe Creative Cloud"],
    processSteps: [
      { title: "Position", detail: "What you stand for and who it is for." },
      { title: "Plan", detail: "Pillars, formats and cadence per channel." },
      { title: "Produce", detail: "Design, video and copy in batches." },
      { title: "Publish", detail: "Scheduled with platform-native formatting." },
      { title: "Engage", detail: "Comments, DMs and community handled daily." },
      { title: "Review", detail: "Monthly analysis and next-month plan." },
    ],
    timeline: "Ongoing monthly",
    pricingModel: "MONTHLY_RETAINER",
    startingPrice: 35000,
    currency: "BDT",
    featured: false,
    position: 8,
    features: [
      { title: "Made for the platform", detail: "Vertical video shot and edited for the feed, not landscape assets cropped down." },
      { title: "Community managed daily", detail: "Comments and DMs answered inside working hours, with escalation for sales-shaped conversations." },
      { title: "Batch production", detail: "A month of content produced in structured sessions, so quality stays consistent." },
      { title: "Measured against pipeline", detail: "Reach is reported; enquiries are the target." },
    ],
    faqs: [
      { question: "Which platforms should we be on?", answer: "Usually fewer than you think. We recommend a maximum of two done properly over four done thinly." },
    ],
  },
  {
    slug: "email-marketing",
    title: "Email Marketing & Automation",
    categorySlug: "growth",
    tagline: "The channel you own, working while you sleep.",
    shortDescription: "Lifecycle flows, campaign programmes and deliverability engineering for lists that actually generate revenue.",
    longDescription: "Email is the only channel where you own the audience. Most businesses use maybe a tenth of it — a newsletter, occasionally.\n\nWe build the lifecycle: welcome, nurture, abandonment, reactivation and post-purchase flows that run automatically, plus the campaign calendar on top. Before any of it, we fix deliverability, because the best email in the spam folder earns nothing.",
    icon: "Mail",
    deliverables: ["Deliverability audit (SPF, DKIM, DMARC)", "List hygiene and segmentation strategy", "Lifecycle automation flows", "Campaign calendar and production", "Responsive template system", "A/B testing programme", "Revenue attribution reporting", "Compliance review (consent, unsubscribe)"],
    technologies: ["Resend", "Klaviyo / Mailchimp", "Customer.io", "Postmark", "DMARC tooling"],
    processSteps: [
      { title: "Audit", detail: "Deliverability, list health and current performance." },
      { title: "Authenticate", detail: "SPF, DKIM and DMARC configured and monitored." },
      { title: "Segment", detail: "Behaviour and lifecycle-stage segments defined." },
      { title: "Automate", detail: "Core flows built and tested." },
      { title: "Campaign", detail: "Ongoing calendar layered on top of automation." },
      { title: "Optimise", detail: "Continuous subject, offer and timing testing." },
    ],
    timeline: "3–5 weeks to build core flows",
    pricingModel: "STARTING_FROM",
    startingPrice: 65000,
    currency: "BDT",
    featured: false,
    position: 9,
    features: [
      { title: "Deliverability first", detail: "Authentication and reputation fixed before volume goes up, so campaigns reach the inbox." },
      { title: "Flows that run without you", detail: "Welcome, nurture, abandonment and win-back automated end to end." },
      { title: "Revenue attributed per flow", detail: "Every automation reports its own contribution, so you know what to invest in." },
      { title: "Consent handled properly", detail: "Opt-in, preference centre and unsubscribe built to comply, not to trick." },
    ],
    faqs: [
      { question: "Our open rates collapsed — why?", answer: "Usually authentication or list hygiene, sometimes Apple Mail Privacy Protection distorting the metric. The audit tells you which within a week." },
    ],
  },
  {
    slug: "graphic-design",
    title: "Brand & Graphic Design",
    categorySlug: "creative",
    tagline: "A visual system, documented so it survives contact with reality.",
    shortDescription: "Brand identity, design systems and campaign assets built as reusable systems rather than one-off files.",
    longDescription: "A logo is not a brand. What you need is a system — type scale, colour tokens, spacing rules, component patterns and the documentation that lets anyone apply it correctly.\n\nWe design that system, then produce the assets that live inside it: the website UI, the campaign creative, the pitch decks and the print pieces.",
    icon: "Palette",
    deliverables: ["Brand discovery and positioning workshop", "Logo and mark design with full export kit", "Colour, type and spacing token system", "Component and UI pattern library", "Brand guidelines document", "Marketing and campaign asset templates", "Social and ad creative kit", "Source files and full handover"],
    technologies: ["Figma", "Adobe Illustrator", "Adobe Photoshop", "After Effects"],
    processSteps: [
      { title: "Discover", detail: "Positioning, audience and the visual territory to own." },
      { title: "Explore", detail: "Distinct directions, presented with rationale." },
      { title: "Refine", detail: "One direction developed to completion." },
      { title: "Systemise", detail: "Tokens, components and rules documented." },
      { title: "Produce", detail: "Asset kits for every channel you use." },
      { title: "Handover", detail: "Source files, guidelines and a working session with your team." },
    ],
    timeline: "4–8 weeks",
    pricingModel: "STARTING_FROM",
    startingPrice: 120000,
    currency: "BDT",
    featured: false,
    position: 10,
    features: [
      { title: "Vector from the start", detail: "Every mark delivered as true vector plus a full raster export kit — favicons, app icons, social avatars." },
      { title: "Design tokens, not screenshots", detail: "Colour and type delivered as tokens developers can implement exactly." },
      { title: "Small-size variants", detail: "Marks tested and adjusted for 16px favicons, not only for the pitch deck." },
      { title: "Documented rules", detail: "Clear-space, minimum sizes, do's and don'ts — so the brand holds up when someone else applies it." },
    ],
    faqs: [
      { question: "Do we get the source files?", answer: "Yes — Figma libraries and Adobe source files, with no ongoing licence to use your own brand." },
    ],
  },
  {
    slug: "ai-automation",
    title: "AI & Business Automation",
    categorySlug: "engineering",
    tagline: "Remove the repetitive work, keep the human judgement.",
    shortDescription: "Practical automation and AI integration for real operational bottlenecks — lead handling, support triage, reporting and document workflows.",
    longDescription: "The value of AI in a services business is rarely a chatbot. It is in the twenty minutes a day someone spends copying data between systems, the enquiry that waits four hours for a first response, the report that takes a full day to assemble each month.\n\nWe map those workflows, automate the mechanical parts, and use language models only where they genuinely beat a rule — always with a human checkpoint on anything that reaches a customer.",
    icon: "Bot",
    deliverables: ["Workflow audit and automation opportunity map", "Integration architecture between your systems", "Lead qualification and routing automation", "AI-assisted drafting with human review steps", "Support triage and knowledge retrieval", "Automated reporting pipelines", "Monitoring, logging and failure handling", "Team training and documentation"],
    technologies: ["Claude API", "OpenAI API", "n8n / Make", "Inngest", "PostgreSQL", "Vector search"],
    processSteps: [
      { title: "Map", detail: "Where time actually goes, measured rather than assumed." },
      { title: "Prioritise", detail: "Rank by hours saved against implementation cost." },
      { title: "Prototype", detail: "One workflow, proven end to end, before scaling." },
      { title: "Integrate", detail: "Connected to your live systems with proper error handling." },
      { title: "Guard", detail: "Human approval on anything customer-facing; full audit logging." },
      { title: "Train", detail: "Your team runs it; we document and hand over." },
    ],
    timeline: "3–8 weeks per workflow",
    pricingModel: "CUSTOM_QUOTE",
    startingPrice: null,
    currency: "BDT",
    featured: true,
    position: 11,
    features: [
      { title: "Measured before and after", detail: "We baseline the hours a workflow costs today so the saving is a number, not a claim." },
      { title: "Human in the loop", detail: "Anything that reaches a client passes a person first. Automation drafts; humans approve." },
      { title: "Fails safely", detail: "Retries, dead-letter queues and alerting, so a provider outage never silently drops work." },
      { title: "Your data stays yours", detail: "No training on your data, clear retention rules, credentials in your own accounts." },
    ],
    faqs: [
      { question: "Is our data used to train models?", answer: "No. We use API access with training disabled and document exactly what is sent, retained and for how long." },
      { question: "What if the AI gets something wrong?", answer: "Human approval gates on anything customer-facing, plus full logging so any output can be traced and corrected." },
    ],
  },
  {
    slug: "conversion-optimisation",
    title: "Conversion Rate Optimisation",
    categorySlug: "growth",
    tagline: "Earn more from the traffic you already have.",
    shortDescription: "Research-led experimentation on the pages that decide revenue — backed by session data, not opinion.",
    longDescription: "Doubling traffic is expensive. Improving conversion on the traffic you already have is usually cheaper and faster, and it compounds with every other channel.\n\nWe combine quantitative analysis, session recordings and user testing to find where intent is being lost, then run structured experiments with enough traffic to actually call a result.",
    icon: "MousePointerClick",
    deliverables: ["Analytics and funnel audit", "Heatmap and session recording analysis", "User testing and survey research", "Prioritised experiment backlog", "A/B test design and implementation", "Statistical analysis and reporting", "Winning variant rollout", "Quarterly CRO roadmap"],
    technologies: ["Microsoft Clarity", "GA4", "Optimizely / GrowthBook", "Hotjar"],
    processSteps: [
      { title: "Measure", detail: "Where users drop, on which devices, from which sources." },
      { title: "Observe", detail: "Recordings and heatmaps on the highest-value paths." },
      { title: "Ask", detail: "Short surveys and moderated tests for the why." },
      { title: "Hypothesise", detail: "A prioritised, evidence-linked backlog." },
      { title: "Test", detail: "Properly powered experiments with pre-agreed success criteria." },
      { title: "Ship", detail: "Winners rolled out; losers documented so they are not retried." },
    ],
    timeline: "Ongoing, 2–4 experiments per month",
    pricingModel: "MONTHLY_RETAINER",
    startingPrice: 50000,
    currency: "BDT",
    featured: false,
    position: 12,
    features: [
      { title: "Research before redesign", detail: "We do not restyle a page and call it a test. Every experiment starts from evidence." },
      { title: "Statistically honest", detail: "Sample size agreed before launch; no calling a winner on day three." },
      { title: "Losses are learning", detail: "Failed tests are documented with the reasoning, so the same idea is not retried in a year." },
      { title: "Privacy-respecting", detail: "Session tools configured to mask personal and payment data." },
    ],
    faqs: [
      { question: "How much traffic do we need to A/B test?", answer: "Roughly a thousand conversions a month on the tested step gives reliable results quickly. Below that we use sequential testing and qualitative research instead." },
    ],
  },
];
